AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  Psycopg2Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: psycopg2-layer/
      CompatibleRuntimes:
        - python3.12
      CompatibleArchitectures:
        - x86_64
    Metadata:
      BuildMethod: makefile